### ISSUE TITLE
Cant post data

### ISSUE THREAD

**Issue by leegang** [snakeye/ConfigManager#4]
![image](https://user-images.githubusercontent.com/2744278/94406048-01b78200-01a4-11eb-80be-21ecdcc13558.png)

The body data is:
```Json
{"Nightscout":{"enabled":true,"server":"http://dededede.com","token":"eddedede"},"TomatoServer":{"enabled":true,"shareid":"defefefefefef"}}
```

**Comment by snakeye** [comment]
Okay, I'll check the issue. Definitely, "204 No Content" should not come with the payload.

**Comment by leegang** [comment]
Sorry, it was my bad.
